cs

diff --git a/template/hooks/php/doctrine/update-schema b/template/hooks/php/doctrine/update-schema
--- a/template/hooks/php/doctrine/update-schema
+++ b/template/hooks/php/doctrine/update-schema
@@ -11,33 +11,33 @@ updateSchema()
 	result=$?
 	case $result in
 		2)
-		  echo "Your schema is not up to date!"
-		  if [ -d "vendor/doctrine/migrations" ]
-		  then
-			 echo "Looks like you're using migrations"
-			 read -p "Do you wish to migrate (y/n) ? " -n 1
-			 if [[ ! $REPLY =~ ^[Yy]$ ]]
-			 then
-				echo "not updating"
-				exit 1
-			 fi
-			 $console doctrine:migrations:migrate
-		  else
-			 echo "Looks like you're not using migrations! the following queries will be run:"
-			 $console doctrine:schema:update --dump-sql --complete
-			 read -p "Do you wish to update the schema (y/n) ? " -n 1
-			 if [[ ! $REPLY =~ ^[Yy]$ ]]
-			 then
-				echo "not updating"
-				exit 1
-			 fi
-			 $console doctrine:schema:update --force --complete
-		  fi
-		  ;;
+			echo "Your schema is not up to date!"
+			if [ -d "vendor/doctrine/migrations" ]
+			then
+				echo "Looks like you're using migrations"
+				read -p "Do you wish to migrate (y/n) ? " -n 1
+				if [[ ! $REPLY =~ ^[Yy]$ ]]
+				then
+					echo "not updating"
+					exit 1
+				fi
+				$console doctrine:migrations:migrate
+			else
+				echo "Looks like you're not using migrations! the following queries will be run:"
+				$console doctrine:schema:update --dump-sql --complete
+				read -p "Do you wish to update the schema (y/n) ? " -n 1
+				if [[ ! $REPLY =~ ^[Yy]$ ]]
+				then
+					echo "not updating"
+					exit 1
+				fi
+				$console doctrine:schema:update --force --complete
+			fi
+			;;
 		3)
-		  $console doctrine:schema:validate
-		  echo "Your schema is invalid, but won't be updated because your mapping has errors. Please Fix them first."
-		  ;;
+			$console doctrine:schema:validate
+			echo "Your schema is invalid, but won't be updated because your mapping has errors. Please Fix them first."
+			;;
 	esac
 }
 
